src/AliseeksFE/Models/Dropship/DropshipAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json;

namespace AliseeksFE.Models.Dropship
{
    public enum AccountStatus
    {
        New, Existing
    }


    public class DropshipAccount
    {
        public int ID { get; set; }
        public string Username { get; set; }
        [JsonConverter(typeof(StringEnumConverter))]
        public AccountStatus Status { get; set; }
        public string Subscription { get; set; }
        public DropshipAccountRules Account { get; set; } = new DropshipAccountRules();
    }

    public class DropshipAccountRules
    {
        public DropshipListingRules Default { get; set; } = DropshipListingRules.Default;
    }

    public class DropshipAccountItem
    {
        public DropshipAccount Account { get; set; }
        public DropshipItemModel Item { get; set; }
    }
}

src/AliseeksFE/Models/Dropship/DropshipIntegration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AliseeksFE.Models.Dropship
{
    public class DropshipIntegration
    {
        public int ID { get; set; }
        public string Service { get; set; }
        public string AccountInfo { get; set; }
    }
}

src/AliseeksFE/Models/Dropship/DropshipItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AliseeksFE.Models.Shopify;

namespace AliseeksFE.Models.Dropship
{
    public class DropshipItem
    {
        public DropshipItemModel Dropshipping { get; set; }
        public ShopifyProductModel Product { get; set; }
    }
}

src/AliseeksFE/Models/Dropship/DropshipItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AliseeksFE.Models.Search;

namespace AliseeksFE.Models.Dropship
{
    public class DropshipItemModel
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public SingleItemRequest Source { get; set; }
        public string ListingID { get; set; }
        public string Listing { get; set; }
        public DropshipListingRules Rules { get; set; }
        public string Image { get; set; }
    }
}

src/AliseeksFE/Models/Dropship/DropshipListingRules.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AliseeksFE.Models.Dropship
{
    public enum PriceRule
    {
        FixedPrice,
        PriceAdjustment,
        PricePercentage,
        None
    }

    public enum StockRule
    {
        FixedStock,
        StockAdjustment,
        None
    }

    public class DropshipListingRules
    {
        public static DropshipListingRules Default
        {
            get
            {
                return new DropshipListingRules()
                {
                    PriceRule = PriceRule.PricePercentage,
                    Price = 10.0m,
                    StockRule = StockRule.StockAdjustment,
                    Stock = 5
                };
            }
        }

        public decimal Price { get; set; }
        public PriceRule PriceRule { get; set; }
        public int Stock { get; set; }
        public StockRule StockRule { get; set; }
    }
}

src/AliseeksFE/Models/Dropship/DropshipOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AliseeksFE.Models.Shopify;

namespace AliseeksFE.Models.Dropship
{
    public class DropshipOrder
    {
        public ShopifyOrder Order { get; set; }
        public DropshipItemModel[] Items { get; set; }
    }
}

src/AliseeksFE/Models/Dropship/DropshipOverview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AliseeksFE.Models.Dropship
{
    public class DropshipOverview
    {
        public DropshipAccount Account { get; set; }
        //public DropshipOrder[] Orders { get; set; } TODO: FUTURE
        public int ProductCount { get; set; }
        public int IntegrationCount { get; set; }
    }
}

src/AliseeksFE/Controllers/DropshipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AliseeksFE.Services.Dropshipping;
using SharpRaven.Core;
using AliseeksFE.Models.Search;
using AliseeksFE.Models.Shopify;
using AliseeksFE.Filters;
using AliseeksFE.Services.Api;
using Newtonsoft.Json;
using AliseeksFE.Services;
using AliseeksFE.Models.Dropship;
using AliseeksFE.Models.Api;
using AliseeksFE.Utility;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AliseeksFE.Controllers
{
    [Authorize]
    [TypeFilter(typeof(DropshipAuthorizationFilter))]
    public class DropshipController : Controller
    {
        private readonly DropshipService dropship;
        private readonly IRavenClient raven;
        private readonly IApiService api;

        private const int productsPerPage = 20;

        public DropshipController(DropshipService dropship, IApiService api, IRavenClient raven)
        {
            this.dropship = dropship;
            this.raven = raven;
            this.api = api;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var overview = await dropship.GetOverview();

            return View(overview);
        }

        public async Task<IActionResult> Add(SingleItemRequest item)
        {
            var response = await dropship.AddProduct(item);

            if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                return RedirectToAction("Integrations");

            return RedirectToAction("Products");
        }

        [HttpGet]
        [Route("[controller]/products/add")]
        public IActionResult AddProduct()
        {
            return View(new DropshipItemModel()
            {
                Source = new SingleItemRequest()
                {
                    Source = "Aliexpress"
                },
                Rules = DropshipListingRules.Default
            });
        }

        [HttpPost]
        [Route("[controller]/products/add")]
        public async Task<IActionResult> AddProduct(DropshipItemModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var response = await dropship.AddProduct(model);

            if(response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                ModelState.AddModelError("All", await response.Content.ReadAsStringAsync());
                return View(model);
            }

            return RedirectToAction("Products");
        }

        [HttpGet]
        [Route("[controller]/products/{itemid}")]
        public async Task<IActionResult> Product(int itemid)
        {
            var dropshipItem = await dropship.GetProduct(itemid);

            return View(dropshipItem.Dropshipping);
        }

        [HttpGet]
        [Route("[controller]/products/{itemid}/add")]
        public async Task<IActionResult> ProductAddToIntegration(int itemid)
        {
            var response = await api.Get(ApiEndpoints.DropshipAddProductIntegration(itemid));

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Products");
            }
            else
            {
                return RedirectToAction("Products");
            }
        }

        [HttpPost]
        [Route("[controller]/products/{itemid}")]
        public async Task<IActionResult> Product(int itemid, [FromForm]DropshipItemModel item)
        {
            item.ID = itemid;

            var json = JsonConvert.SerializeObject(item);
            var response = await api.Put(ApiEndpoints.DropshipUpdateProduct, new JsonContent(json));

            if(response.IsSuccessStatusCode)
            {
                return RedirectToAction("Products");
            }
            else
            {
                var message = await response.Content.ReadAsStringAsync();
                ModelState.AddModelError("All", message);
                return View(item);
            }
        }

        [Route("[controller]/products/{itemid}/delete")]
        public async Task<IActionResult> ProductDelete(int itemid)
        {
            var response = await api.Delete(ApiEndpoints.DropshipProductDelete(itemid));

            if(response.IsSuccessStatusCode)
            {
                return RedirectToAction("Products");
            }
            else
            {
                return RedirectToAction("Products");
            }
        }

        public async Task<IActionResult> Integrations()
        {
            var integrations = await dropship.GetIntegrations();

            return View(integrations);
        }

        [HttpGet]
        [Route("[controller]/integrations/shopify")]
        public IActionResult IntegrateShopify()
        {
            return View("ShopifyIntegration");
        }

        [HttpPost]
        [Route("[controller]/integrations/shopify")]
        public async Task<IActionResult> IntegrateShopify(string shop)
        {
            var oauthRequest = await dropship.GetShopifyOAuth(shop);

            if (oauthRequest == null)
            {
                ModelState.AddModelError("OAuth Failed", "Something failed requesting OAuth info from API");
                return View("ShopifyIntegration");
            }
            else
            {
                return Redirect(oauthRequest.Uri);
            }
        }

        [Route("[controller]/integration/{id}/delete")]
        public async Task<IActionResult> DeleteIntegration(int id)
        {
            var username = HttpContext.User.Identity.Name;

            await dropship.DeleteIntegration(id);

            return RedirectToAction("Integrations");
        }

        [HttpGet]
        [Route("[controller]/integrations/shopify/oauth")]
        public async Task<IActionResult> IntegrateShopifyOAuth([FromQuery]ShopifyOAuthResponse response)
        {
            response.Query = HttpContext.Request.QueryString.Value.Substring(1); //remove leading ?

            await dropship.CompleteShopifyOAuth(response);

            return RedirectToAction("Integrations");
        }

        [HttpGet]
        [Route("[controller]/ajax/aliexpress")]
        public async Task<IActionResult> AjaxAliexpressVerify(string link)
        {
            var response = await api.Get(ApiEndpoints.SearchSingle(link, "Aliexpress"));

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                var product = JsonConvert.DeserializeObject<ItemDetail>(json);
                if (product == null)
                    return NotFound();

                return PartialView("Partials/AliexpressVerify", product);
            }

            return NotFound();
        }

        [HttpGet]
        [Route("[controller]/ajax/shopify")]
        public async Task<IActionResult> AjaxShopifyVerify(string listingid)
        {
            var response = await api.Get(ApiEndpoints.DropshipIntegrationGetProduct("Shopify", listingid));

            if(response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                var product = JsonConvert.DeserializeObject<ShopifyProductModel>(json);
                return PartialView("Partials/ShopifyVerify", product);
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Products(int page = 1)
        {
            var response = await api.Get(ApiEndpoints.DropshipGetProducts(productsPerPage * (page - 1), productsPerPage));

            var products = new DropshipItem[0];

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                products = JsonConvert.DeserializeObject<DropshipItem[]>(json);
            }

            //Add total count for pagination
            ViewBag.MaxCount = response.Headers.Contains("X-Total-Count") ? Convert.ToInt32(response.Headers.GetValues("X-Total-Count").First()) : productsPerPage;
            ViewBag.Page = page;
            ViewBag.ItemsPerPage = productsPerPage;

            return View(products);
        }
    }
}

src/AliseeksFE/Views/Dropship/AddProduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    Layout = "_DropshippingLayout";
}

@model DropshipItemModel

<div class="row">
    <div class="col-md-6">
        <form id="item-form" asp-controller="Dropship" asp-action="AddProduct" method="post" class="form-horizontal">
            <p class="lead">Add a Dropshipping Product</p>
            <div asp-validation-summary="All" class="text-danger"></div>
            <input class="hidden" asp-for="Source.Source" />
            <div class="form-group">
                <label class="control-label">Aliexpress Link: </label>
                <input class="form-control" asp-for="Source.Link" placeholder="https://www.aliexpress.com/item/10-PCS-LOT-HOT-SALE-GDT-DC-12V-Brushless-Cooling-Fan-40mm-10mm-free-shipping/1776219605.html" />
            </div>
            <input asp-for="Source.Source" class="hidden" />
            <div class="form-group">
                <label class="control-label">Price Adjustment: </label>
                <div class="input-group">
                    <span id="price-unit" class="input-group-addon">$</span>
                    <input asp-for="Rules.Price" class="form-control" placeholder="$" />
                </div>
            </div>
            <div class="form-group">
                <select asp-for="Rules.PriceRule" onchange="priceDropdownChange" class="dropdown form-control input-sm">
                    <option value="0">Static</option>
                    <option value="1">Margin</option>
                    <option value="2">Percentage</option>
                    <option value="3">None</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Stock Adjustment:</label>
                <div class="input-group">
                    <span class="input-group-addon">-</span>
                    <input asp-for="Rules.Stock" class="form-control" placeholder="" type="number" />
                </div>
            </div>
            <div class="form-group">
                <select asp-for="Rules.StockRule" class="dropdown form-control input-sm">
                    <option value="0">Fixed Stock</option>
                    <option value="1">Margin</option>
                    <option value="2">None</option>
                </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
</div>

src/AliseeksFE/Views/Dropship/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    Layout = "_DropshippingLayout";
}

@model DropshipOverview

    <h4>Overview</h4>
    <p class="text-muted">Subscription: @Model.Account.Subscription</p>

    <hr />

    <p>Integrations: @Model.IntegrationCount</p>
    <p>Products: @Model.ProductCount / 500</p>

    @if (Model.IntegrationCount == 0)
    {
        <h4>
            Add an integration to get started dropshipping today!
        </h4>
    }

src/AliseeksFE/Views/Dropship/Product.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_DropshippingLayout";
}

@model DropshipItemModel

<div class="row">
    <div class="col-md-6">
        <form id="item-form" asp-controller="Dropship" asp-action="Product" method="post" class="form-horizontal">
            <p class="lead">Manage Rules</p>
            <div asp-validation-summary="All" class="text-danger"></div>
            <input class="hidden" asp-for="Source.Source" />
            <input asp-for="Source.Link" class="hidden" placeholder="https://www.aliexpress.com/item/10-PCS-LOT-HOT-SALE-GDT-DC-12V-Brushless-Cooling-Fan-40mm-10mm-free-shipping/1776219605.html" />
            <input asp-for="Listing" class="hidden" />
            <input asp-for="ListingID" class="hidden" />
            <div class="form-group">
                <label class="control-label">Price Adjustment: </label>
                <div class="input-group">
                    <span id="price-unit" class="input-group-addon">$</span>
                    <input asp-for="Rules.Price" class="form-control" placeholder="$" />
                </div>
            </div>
            <div class="form-group">
                <select asp-for="Rules.PriceRule" onchange="priceDropdownChange" class="dropdown form-control input-sm">
                    <option value="0">Static</option>
                    <option value="1">Margin</option>
                    <option value="2">Percentage</option>
                    <option value="3">None</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Stock Adjustment:</label>
                <div class="input-group">
                    <span class="input-group-addon">-</span>
                    <input asp-for="Rules.Stock" class="form-control" placeholder="" type="number" />
                </div>
            </div>
            <div class="form-group">
                <select asp-for="Rules.StockRule" class="dropdown form-control input-sm">
                    <option value="0">Fixed Stock</option>
                    <option value="1">Margin</option>
                    <option value="2">None</option>
                </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Apply</button>
            </div>
        </form>
    </div>
</div>

@section scripts {
    <script>
        function ajaxVerifyShopify(event) {
            var link = $("[name='ListingID']").val();

            $.ajax({
                url: "/dropship/ajax/shopify?listingid=" + link,
                method: 'GET',
                success: success,
                error: error
            });

            function success(data) {
                $('#listing-verify').empty();
                $('#listing-verify').append('OKAY');
                $('#listing-verify-content').empty();
                $('#listing-verify-content').append(data);
            }

            function error() {
                $('#listing-verify').empty();
                $('#listing-verify').append('NOT OKAY');
            }

            event.preventDefault();
        }

        function ajaxVerifyAliexpress(event)
        {
            var link = $("[name='Source.Link']").val();

            $.ajax({
                url: "/dropship/ajax/aliexpress?link=" + link,
                method: 'GET',
                success: success,
                error: error
            });

            function success(data)
            {
                $('#aliexpress-verify').empty();
                $('#aliexpress-verify').append('OKAY');
                $('#source-verify-content').empty();
                $('#source-verify-content').append(data);
            }

            function error()
            {
                $('#aliexpress-verify').empty();
                $('#aliexpress-verify').append('NOT OKAY');
            }

            event.preventDefault();
        }

        $(function () {
            $('#aliexpress-verify').click(ajaxVerifyAliexpress);
            $('#listing-verify').click(ajaxVerifyShopify);

            $("[name='Rules.PriceRule']").change(function() {
                var dropdown = $("[name='Rules.PriceRule']");
                switch(dropdown.val())
                {
                    case '3':
                        $("[name='Rules.Price']").prop('disabled', true);
                        break;

                    case '2':
                        $('#price-unit').text('%');
                        $("[name='Rules.Price']").attr('placeholder', '10.0%');
                        $("[name='Rules.Price']").prop('disabled', false);
                        break;

                    default:
                        $('#price-unit').text('$');
                        $("[name='Rules.Price']").attr('placeholder', '$10.00');
                        $("[name='Rules.Price']").prop('disabled', false);
                        break;
                }
            });

            $("[name='Rules.StockRule']").change(function () {
                var dropdown = $("[name='Rules.StockRule']");
                switch (dropdown.val()) {
                    case '2':
                        $("[name='Rules.Stock']").prop('disabled', true);
                        break;

                    default:
                        $("[name='Rules.Stock']").prop('disabled', false);
                        break;
                }
            });
        });

        $(priceDropdownChange($('[onchange="priceDropdownChange"]')));

        function priceDropdownChange(target) {
            var dropdown = $(target);

            if(dropdown.val() == 2)
            {
                $('#price-unit').text('%');
            }
            else {
                $('#price-unit').text('$');
            }
        }

</script>
}

src/AliseeksFE/Views/Dropship/Products.cshtml
@model DropshipItem[]
@inject PaginationInject pagination
@inject DropshipRuleInject rules

@{
    var page = ViewBag.Page;
    var maxCount = ViewBag.MaxCount;
    var itemsPerPage = ViewBag.ItemsPerPage;
    Layout = "_DropshippingLayout";
}

<div class="row">
    <div class="col-md-12 col-center">
        <div class="pull-right">
            <a asp-controller="Dropship" asp-action="AddProduct" class="btn btn-success">+ Add Product</a>
        </div>
    </div>
</div>
<hr/>
<div class="col-md-12 col-center">
    @if (Model == null || Model.Length == 0)
    {
        <div class="alert alert-info text-center">
            <p>No items listed yet! You can add dropshipping items through Aliseeks <a asp-controller="Home" asp-action="Index">Search</a>.</p>
        </div>
    }
    else
    {
        @foreach (var item in Model)
        {
            <div class="row row-centered" style="margin-bottom:10px;">
                <div class="product">
                    <div class="col-xs-11">
                        <img class="dropship-image" src="@item.Dropshipping.Image" alt="@item.Dropshipping.Source.Title" />
                        <div class="col-md-6">
                            <a href="@item.Dropshipping.Source.Link" class="dropship-title">@item.Dropshipping.Source.Title</a>
                            <br />
                            <br />
                            <p>
                                Pricing:
                                <strong>
                                    @switch (item.Dropshipping.Rules.PriceRule)
                                    {
                                        case PriceRule.PriceAdjustment:
                                            if (item.Dropshipping.Rules.Price > 0)
                                            {
                                                <span style="color:green;"><i class="fa fa-angle-up" aria-hidden="true"></i> $ @item.Dropshipping.Rules.Price</span>
                                            }
                                            else
                                            {
                                                <span style="color:red;"><i class="fa fa-angle-down" aria-hidden="true"></i> $ @item.Dropshipping.Rules.Price</span>
                                            }
                                            break;

                                        case PriceRule.PricePercentage:
                                            if (item.Dropshipping.Rules.Price > 0)
                                            {
                                                <span style="color:green;"><i class="fa fa-angle-up" aria-hidden="true"></i> @item.Dropshipping.Rules.Price %</span>
                                            }
                                            else
                                            {
                                                <span style="color:red;"><i class="fa fa-angle-down" aria-hidden="true"></i> @item.Dropshipping.Rules.Price %</span>
                                            }
                                            break;

                                        case PriceRule.FixedPrice:
                                            <span>$ @item.Dropshipping.Rules.Price</span>
                                            break;

                                        case PriceRule.None:
                                            <span>None</span>
                                            break;
                                    }
                                </strong>
                            </p>
                            <p>
                                    Stock:
                                <strong>
                                    @switch (item.Dropshipping.Rules.StockRule)
                                    {
                                        case StockRule.StockAdjustment:
                                            if (item.Dropshipping.Rules.Stock > 0)
                                            {
                                                <span style="color:red;"><i class="fa fa-angle-down" aria-hidden="true"></i> @item.Dropshipping.Rules.Stock</span>
                                            }
                                            else
                                            {
                                                <span style="color:green;"><i class="fa fa-angle-up" aria-hidden="true"></i> @item.Dropshipping.Rules.Stock</span>
                                            }
                                            break;

                                        case StockRule.FixedStock:
                                            <span> @item.Dropshipping.Rules.Stock</span>
                                            break;

                                        case StockRule.None:
                                            <span>None</span>
                                            break;

                                    }
                                </strong>
                            </p>
                        </div>
                        <div class="col-md-3">
                            @if (item.Product != null)
                            {
                                @foreach (var variant in item.Product.Variants)
                                {
                                    <p class="dropship-price">$@variant.Price</p>
                                    <a class="btn-default" href="@item.Product.Link"><i class="fa fa-external-link" aria-hidden="true"></i> View</a>
                                }
                            }
                            else
                            {
                                <a asp-controller="dropship" asp-action="ProductAddToIntegration" asp-route-itemid="@item.Dropshipping.ID" class="btn btn-primary">Add!</a>
                            }
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <a asp-controller="Dropship" asp-action="Product" asp-route-itemid="@item.Dropshipping.ID" class="btn btn-default"  data-toggle="tooltip" data-placement="bottom" title="Manage Rules"><i class="fa fa-gear"></i></a>
                        <br />
                        <br />
                        <a asp-controller="Dropship" asp-action="ProductDelete" asp-route-itemid="@item.Dropshipping.ID" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                    </div>
                </div>
            </div>
        }
    }
</div>

<div class="row row-centered">
    <div class="col-xs-12 text-center">
        <div class="btn-group">
            <ul class="pagination">
                @{
                    foreach (int pageNum in pagination.GetPages(page, maxCount, itemsPerPage))
                    {
                        if (pageNum == page)
                        {

                            <li class="active">
                                <a asp-controller="Dropship" asp-action="Products" asp-route-page="@pageNum">@pageNum</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a asp-controller="Dropship" asp-action="Products" asp-route-page="@pageNum">@pageNum</a>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </div>
</div>

src/AliseeksFE/Views/Dropship/ShopifyIntegration.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{

    Layout = "_DropshippingLayout";
}

<div class="row">
    <div class="col-md-offset-3 col-md-5">
        <br />
        <br />
        <img src="~/images/shopifylogo.png" alt="shopify" />
        <br />
        <br />
        <form method="post">
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="control-label">Store Name:</label>
                    <input class="form-control input-sm" placeholder="MyWonderfulStoreName" name="shop" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Integrate</button>
                </div>
            </div>
        </form>
    </div>
</div>